### ISSUE TITLE
Questions. Using DAFdiscovery with nontarget screening data

### ISSUE THREAD

**Issue by JeanFroment** [RicardoMBorges/DAFdiscovery#1]
Hello,

thank you very much for this promising tool. I have few question before using it for my research.

Do you think that DAFdiscovery would be relevant for data from nontarget screening (when we collect MS1 and MS2 data from all the molecules we can ionized in our sample)?
 
If so, do you think the pipeline can be use with MS data collected in different ionization modes and maybe with MS data coming from different instruments (like LC and GC)? If I am not mistaken I think I only saw MS data collected in one ionization mode in the examples with the tutorials.
 
In that optic do you think the data should be scaled before calculating the correlation between MS signals and bioactivity? I am thinking that scaling the MS Areas by unit variance before running the script would avoid easily ionized molecules having a too important weight on the model compare to other molecules with a less intense signal.

One last thing: in the script for the case II (MS data and bioactivity) I noticed that the last correlation plot of MS feature was not loading properly  because the column "corr_Bioact" was not renamed in the file corrDF. I fixed it by adding "corrDF2.columns.values[1] = "corr_BioAct"" before exporting MSinfo_corr.

Thanks for the help.
Jean

**Comment by RicardoMBorges** [comment]
Hi Jean, I'll organize your questions into a list here and I'll try to reply to each. This is an effort in progress, and I hope you can help me get there! Thank you for your interest.

(1) Do you think that DAFdiscovery would be relevant for data from nontarget screening (when we collect MS1 and MS2 data from all the molecules we can ionized in our sample)?
>> Yes, in fact the data I used was all for nontarget screenings. But it will use only the intensities (or AUC of the deconvoluted xC-MS features) from the MS1. So, what I recommend is to process/deconvolute the xC(LC or GC)-MS data so that you have the intensities/AUC of the MS1 features and the MS2 data (as .mgf maybe) organized according to the number of each MS1 features. By doing so, you will be able to index the highly correlated MS1 feature directly to the MS2 data.

(2)If so, do you think the pipeline can be use with MS data collected in different ionization modes and maybe with MS data coming from different instruments (like LC and GC)? If I am not mistaken I think I only saw MS data collected in one ionization mode in the examples with the tutorials.
>> I never tried to run this with data from LC and GC in the same goal. So, do you want to correlate peaks from LC to GC? If this is the case, we can create another Notebook to organize that; it shouldn't be too hard.

(3)the data should be scaled before calculating the correlation between MS signals and bioactivity?
>> Ok. That is a question to be tackled. I'm not sure if we need to Normalize or Scale the data before running the correlations. I guess we need to dive into it a little bit and try different approaches; it will probably depend on the case of study.

(4)One last thing: in the script for the case II (MS data and bioactivity) I noticed that the last correlation plot of MS feature was not loading properly because the column "corr_Bioact" was not renamed in the file corrDF. I fixed it by adding "corrDF2.columns.values[1] = "corr_BioAct"" before exporting MSinfo_corr.
> Great. Thanks; yes, there might be some things like this to be fixed during the course of others using DAFdiscovery. 

I hope this helps.

**Comment by JeanFroment** [comment]
Thank you very much for the quick replies.

Regarding point #2 I am actually interested in combining data from three different instruments: data from LC (nontargeted screening), ICP-MS, and Ion Chromatography. If I can use all chemical signals together (maybe as the "MS data") I think that scaling will be necessary.

Thanks a lot for the help

**Comment by RicardoMBorges** [comment]
Of course. Let us chat and if it is the case, we'll design another Notebook that will fit your case (a "spinoff"). That will be interesting. 
Thanks

**Comment by stefhk3** [comment]
Sounds great. I can help with the implementation.
